config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # devise_scope :user do
  #   get 'my_account', to: 'users/registrations#edit', as: :my_account
  # end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"
  resources :items, only: [:index, :show]
  
  resources :basket_items, only: [:create, :update, :destroy]
  resource :basket, only: [:show]
  
  resources :wishlist_items, only: [:create, :destroy]
  resource :wishlist, only: [:show]
  
  resources :orders, only: [:new, :create, :index, :show] do
    member do
      get :confirmation
      delete :cancel
      patch :save_address
      patch :save_delivery_date 
    end
    resources :payments, only: [:new, :create] do
      get :success, on: :collection
    end
  end

  resources :deliveries, only: [] do
    collection do
      get :available_dates
    end
  end

  get 'api/address_lookup', to: 'addresses#lookup'
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user

  has_many :basket_items, dependent: :destroy
  has_many :items, through: :basket_items

  def clean_up_expired_items
    basket_items.includes(:item).each do |basket_item|
      next unless basket_item.expired?

      ActiveRecord::Base.transaction do
        basket_item.item.increment!(:stock, basket_item.quantity)
        basket_item.destroy
      end
    end
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  include OrderCalculations
  def show
    @basket = current_user.basket
    @basket.clean_up_expired_items
    @basket_items = @basket.basket_items.includes(:item).order(:created_at)

    # Remove expired items and calculate remaining time
    @basket_items.each do |basket_item|
      next unless basket_item.expired?

      ActiveRecord::Base.transaction do
        basket_item.item.increment!(:stock, basket_item.quantity)
        basket_item.destroy
      end
    end

    # Remove expired orders if any
    current_user.orders.each do |order|
      order.destroy if order.expired?
    end

    # Reload basket items after cleanup
    @basket_items = @basket.basket_items.includes(:item).order(:created_at)
    @pending_order = current_user.orders.pending.first
    calculate_totals

    respond_to do |format|
      format.html
      format.json do
        html = render_to_string(
          partial: 'basket_summary',
          formats: [:html],
          layout: false
        )
        render json: {
          success: true,
          html: html
        }
      rescue StandardError => e
        render json: {
          success: false,
          error: e.message
        }, status: :internal_server_error
      end
    end
  end
end

app/views/baskets/_basket_item.html.erb
<div class="flex items-center bg-slate-50 drop-shadow m-2" data-controller="basket">
  <%= link_to item_path(basket_item.item) do %>
    <img src="<%= basket_item.item.image_url %>"
          alt="Item image"
          class="w-28 h-28 flex-shrink-0 object-contain p-1 mr-2 hover:brightness-125 transition-all">
  <% end %>

  <div class="flex flex-grow justify-between mr-2">
    <div class="flex flex-col flex-grow">
      <div class="flex justify-between items-center">
        <p class="pt-2 hover:text-lighterBlue">
          <%= link_to item_path(basket_item.item) do %>
            <%= basket_item.item.name %>
          <% end %>
        </p>

        <div>
        <%= button_to basket_item_path(basket_item),
            # 'Remove all',
            method: :delete,
            class: 'mx-2 mt-2 text-red-700 hover:text-red-400',
            data: { confirm: 'Are you sure?' } do %>
              <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>

      <div class="flex pt-2 items-center">
        <% if basket_item.item.stock.zero? %>
          <p class="text-red-500">Out of stock</p>
          <% else %>
          <p class="mb-0.5">Quantity:&nbsp;</p>
          <%= form_with(model: basket_item, method: :patch,
              data: { action: "submit->basket#submitForm" }) do |form| %>
            <%= form.number_field :quantity, 
                # min: 1, 
                max: basket_item.item.stock, 
                value: basket_item.quantity, 
                class: 'w-10 bg-slate-50 text-center', 
                data: { 
                  basket_target: "quantityInput", 
                  action: "input->basket#validateQuantity" 
                } %>
            <%= form.submit "Update", class: 'btn-secondary cursor-pointer' %>
          <% end %>
        <% end %>
      </div>

      <div class="flex justify-between items-center">
        <p class="py-2">
          £<%= basket_item.item.price %> per unit
        </p>
        <%# Timer Section %>
        <% if basket_item.remaining_time > 0 %>
          <div class="text-sm text-secondaryText py-2 pr-2">
            Time left: 
            <span id="timer-<%= basket_item.id %>"
                  data-timer-target="timer" 
                  data-expiration-time="<%= basket_item.remaining_time.to_i %>">
              Loading...
            </span>
          </div>
        <% end %>
      </div>
    </div>  
  </div>
</div>

app/views/baskets/_basket_summary.html.erb
<h2 class="text-xl font-semibold pb-2">Order Summary</h2>
<ul class="pb-4">
  <% @basket_items.each do |basket_item| %>
    <li class="flex justify-between border-b py-2">
      <span><%= basket_item.item.name %> (x<%= basket_item.quantity %>)</span>
      <span>£<%= (basket_item.item.price * basket_item.quantity) %></span>
    </li>
  <% end %>
</ul>
<div class="flex justify-between font-bold text-lg border-t pt-2">
  <span>Subtotal:</span>
  <span>£<%= @basket_items.sum { |item| item.item.price * item.quantity } %></span>
</div>
<div class="flex justify-between text-lg py-1">
  <span>Delivery fee:</span>
  <span>£<%= @delivery %></span>
</div>
<div class="flex justify-between font-bold text-lg pt-2">
  <span>Total:</span>
  <span>£<%= @total %></span>
</div>
<div class="pt-4">
  <%#= link_to 'Proceed to Payment', new_order_path, class: 'btn-primary w-full text-center' %>
  <%= form_with(url: orders_path, local: true) do |form| %>
    <%= form.submit 'Proceed to Payment', class: 'btn-primary w-full text-center' %>
  <% end %>
</div>

app/views/baskets/_pending_order.html.erb
<div class="bg-slate-50 p-2 m-2 drop-shadow">
  <div class="flex items-center" data-controller="">
    <h2 class="text-xl font-semibold pb-2">Pending Order</h2>

    <%# Timer Section for Pending Order %>
    <% if @pending_order.time_left > 0 %>
      <div class="text-sm text-secondaryText pb-1 pl-4">
        Time left: 
        <span id="order-timer-<%= @pending_order.id %>"
              data-timer-target="timer" 
              data-expiration-time="<%= @pending_order.time_left.to_i %>">
          Loading...
        </span>
      </div>
    <% end %>
  </div>
  <ul class="pb-4">
    <% @pending_order.order_items.each do |order_item| %>
      <li class="flex justify-between border-b py-2">
        <span><%= order_item.item.name %> (x<%= order_item.quantity %>)</span>
        <span>£<%= (order_item.price * order_item.quantity) %></span>
      </li>
    <% end %>
  </ul>
  <div class="flex justify-between py-1">
    <span>Delivery fee:</span>
    <span>£<%= @delivery %></span>
  </div>
  <div class="flex justify-between font-bold text-lg pt-2">
    <span>Total:</span>
    <span>£<%= @pending_order.total_amount %></span>
  </div>
  <div class="flex justify-between mt-4" id="payment-actions">
    <% if @pending_order.time_left <= 0 %>
      <%= link_to 'Create New Order',
                  basket_path,
                  class: 'btn-primary text-center whitespace-nowrap mr-2 opacity-50 cursor-not-allowed',
                  disabled: true %>
    <% else %>
      <%= link_to 'Resume Payment',
                  new_order_payment_path(@pending_order),
                  class: 'btn-primary text-center whitespace-nowrap mr-2',
                  data: { 
                    turbo: false,
                    disable_with: "Processing..." 
                  } %>
    <% end %>

    <div class="flex flex-col items-start">
      <%= button_to 'Cancel Order',
                    cancel_order_path(@pending_order),
                    method: :delete,
                    class: 'btn-tertiary',
                    data: { 
                      # turbo_confirm: 'Are you sure you want to cancel this order?',
                      # disable_with: "Cancelling..."
                    } %>
      <p class="text-center text-secondaryText text-xs">Items are still saved <br> to your basket</p>
    </div>
  </div>
</div>

app/views/baskets/show.html.erb
<div class="p-4 flex flex-col lg:flex-row" data-controller="timer page-refresh">
  <div class="w-full lg:w-1/2">
    <h1 class="font-bold text-3xl p-1 text-darkBlue">My Basket</h1>
    <% if @basket_items.any? %>
      <% @basket_items.each do |basket_item| %>
        <%= render 'basket_item', basket_item: basket_item %>
      <% end %>

    <% else %>
      <p class="text-center mt-4">Your basket is empty</p>
    <% end %>
    <%= link_to 'Continue Shopping', items_path, class: 'btn-secondary m-2' %>
  </div>

  <div class="w-full lg:w-1/2">
    <h1 class="font-bold text-3xl p-1 text-darkBlue">Checkout</h1>

    <% if @pending_order %>
      <%= render 'pending_order' %>
    <% elsif @basket_items.any? %>
      <div class="bg-slate-50 p-2 m-2 drop-shadow order-summary">
        <%= render 'basket_summary' %>
      </div>
    <% else %>
      <p class="text-center mt-4">No items to checkout</p>
    <% end %>
  </div>
</div>