config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # devise_scope :user do
  #   get 'my_account', to: 'users/registrations#edit', as: :my_account
  # end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"
  resources :items, only: [:index, :show]
  
  resources :basket_items, only: [:create, :update, :destroy]
  resource :basket, only: [:show]
  
  resources :wishlist_items, only: [:create, :destroy]
  resource :wishlist, only: [:show]
  
  resources :orders, only: [:new, :create, :index, :show] do
    member do
      get :confirmation
      delete :cancel
      patch :save_address
      patch :save_delivery_date 
    end
    resources :payments, only: [:new, :create] do
      get :success, on: :collection
    end
  end

  resources :deliveries, only: [] do
    collection do
      get :available_dates
    end
  end

  get 'api/address_lookup', to: 'addresses#lookup'
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<div id="flash-messages">
  <% flash.each do |type, message| %>
    <div class="flash-message <%= "flash-#{type}" %> <%= type == 'notice' ? 'flash-notice' : 'flash-alert' %>" data-controller="flash-message">
      <span class="flash-message-text"><%= message %></span>
      <button class="flash-close-btn" data-action="click->flash-message#hideMessage">
        <i class="fas fa-times"></i>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="flex justify-around bottom-0 w-full shadow-sm p-6 mt-6 bg-darkBlue text-background text-sm">
  <div>
    <%# <p>Permess House, Princess Way,</p> %>
    <%# <p>Prudhoe, NE42 6HD</p> %>
    <p>Address line 1</p>
    <p>Address line 2</p>
    <%# &nbsp; %>
    <p><span class="font-bold">Tel:</span> <%#01661836717%></p>
    <p><span class="font-bold">Mob:</span> <%#07710714217%></p>
  </div>

  <div>
    <%# <p>St Nicholas Street,</p> %>
    <%# <p>Carlisle, CA1 2EF</p> %>
    <p>Alt address line 1</p>
    <p>Alt address line 2</p>
    <%# &nbsp; %>
    <p><span class="font-bold">Tel:</span> <%#01228544822%></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="flex justify-between items-center fixed top-0 z-50 w-full bg-background shadow-sm p-4">
  <h1 class="text-2xl font-bold text-darkBlue hover:text-lighterBlue">
    <%= link_to 'Surplus Stock', root_path %>
  </h1>
  <div class="flex justify-center items-center space-x-4">
    <% if user_signed_in? %>
      <p>
        <%= link_to wishlist_path do %>
          <i class="fa-solid fa-heart fa-lg p-2 text-darkBlue <%= 'text-lighterBlue' if current_page?(wishlist_path) %> hover:text-lighterBlue"></i>
        <% end %>
      </p>
      <p>
        <%= link_to basket_path do %>
          <i class="fa-solid fa-cart-shopping fa-lg p-2 text-darkBlue <%= 'text-lighterBlue' if current_page?(basket_path) %> hover:text-lighterBlue"></i>
        <% end %>
      </p>
      <div class="relative">
        <!-- Dropdown Button -->
        <button 
          id="menu-button" 
          class="flex items-center p-2 rounded focus:outline-none text-darkBlue">
          <i class="fa-solid fa-bars fa-lg hover:text-lighterBlue"></i>
        </button>

        <!-- Dropdown Menu -->
        <div 
          id="menu-dropdown" 
          class="absolute right-0 mt-2 w-48 bg-background rounded shadow-lg z-10 hidden">
          <%= link_to "My account", edit_user_registration_path, class: 'block px-4 py-2 text-primaryText hover:bg-gray-200' %>
          <%= link_to "Order History", orders_path, class: 'block px-4 py-2 text-primaryText hover:bg-gray-200' %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'block w-full text-left px-4 py-2 text-primaryText hover:bg-gray-200' %>
        </div>
      </div>
    <% else %>
      <p>
        <%= link_to 'Sign in', new_user_session_path, class: 'btn-secondary' %>
        <%# or %>
        <%#= link_to 'Sign up', new_user_registration_path, class: 'btn-secondary' %>
      </p>
    <%  end %>
  </div>
</div>