config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # devise_scope :user do
  #   get 'my_account', to: 'users/registrations#edit', as: :my_account
  # end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"
  resources :items, only: [:index, :show]
  
  resources :basket_items, only: [:create, :update, :destroy]
  resource :basket, only: [:show]
  
  resources :wishlist_items, only: [:create, :destroy]
  resource :wishlist, only: [:show]
  
  resources :orders, only: [:new, :create, :index, :show] do
    member do
      get :confirmation
      delete :cancel
      patch :save_address
      patch :save_delivery_date 
    end
    resources :payments, only: [:new, :create] do
      get :success, on: :collection
    end
  end

  resources :deliveries, only: [] do
    collection do
      get :available_dates
    end
  end

  get 'api/address_lookup', to: 'addresses#lookup'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  has_many :basket_items, dependent: :destroy
  has_many :baskets, through: :basket_items
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_many :wishlist_items, dependent: :destroy
  has_many :wishlists, through: :wishlist_items

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
                  against: { name: 'A', description: 'B' },
                  using: {
                    tsearch: { prefix: true, dictionary: "english" }
                    # trigram: { threshold: 0.1 }
                  }

  def stock_available?(requested_quantity)
    stock >= requested_quantity
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_item, only: [:show]
  before_action :store_user_location!, only: %i[index show]
  def index
    # Search functionality
    if params[:query].present?
      @items = Item.search_by_name_and_description(params[:query])

      # apply the order differently for search results
      case params[:sort_by]
      when 'price_asc'
        @items = @items.reorder(price: :asc)
      when 'price_desc'
        @items = @items.reorder(price: :desc)
      when 'name_asc'
        @items = @items.reorder(name: :asc)
      when 'name_desc'
        @items = @items.reorder(name: :desc)
      end
    else
      # get all items with sorting when no search query
      @items = Item.all

      case params[:sort_by]
      when 'price_asc'
        @items = @items.order(price: :asc)
      when 'price_desc'
        @items = @items.order(price: :desc)
      when 'name_asc'
        @items = @items.order(name: :asc)
      when 'name_desc'
        @items = @items.order(name: :desc)
      end
    end

    # show a message if no results
    flash.now[:notice] = "No results found" if @items.empty?
  end

  def show
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end
end

app/views/items/_item_details.html.erb
<div data-controller="basket">
  <p class="pb-2"><%= @item.name %></p>
  <div class="pb-2 flex items-center">
    <p>
      £<%= @item.price %> &nbsp; &nbsp;
    </p>
    <p>
      <%= button_to "Add to Wishlist", wishlist_items_path(item_id: @item.id), method: :post, class: 'btn-secondary' %>
    </p>
  </div>
  <p class="pb-2"><%= @item.description %></p>
  <p class="pb-2" data-basket-target="stockDisplay">Stock remaining: <%= @item.stock%></p>
  <p class="pb-2">Dimensions: </p>

  <div class="w-full pb-2 flex justify-between">
    <%= form_with url: basket_items_path(item_id: @item.id), 
          method: :post, class: 'flex items-start',
          data: { action: "submit->basket#submitForm" } do |form| %>
      <div class="flex py-2">
        <p>Quantity:&nbsp;</p>
        <input type="number"
                name="quantity"
                value="1"
                min="1"
                max="<%= @item.stock %>"
                class="w-16 text-center bg-background"
                data-basket-target="quantityInput"
                data-action="input->basket#updateHiddenQuantity">
      </div>
      <%= form.hidden_field :quantity, 
          data: { basket_target: "hiddenQuantity" } %>
      <div class="flex flex-col items-center">
        <%= form.submit "Add to basket", class: 'btn-primary ml-2' %>
        <p class="text-center text-secondaryText text-xs">Reserves item for <br> 30 minutes</p>
      </div>
    <% end %>
  </div>

</div>

app/views/items/_item_list.html.erb
<div class="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 w-full">
  <% @items.each do |item| %>
    <div class="flex flex-col max-w-65 bg-slate-50 drop-shadow transform transition-transform hover:scale-105" 
         data-controller="basket">
      <div class="flex-grow">
        <%= link_to item_path(item, query: params[:query]) do %>
          <% if item.image_url.present? %>
            <div class="mx-2 mt-2 h-64 overflow-hidden">
            <%= image_tag item.image_url,
              class: "w-full object-cover hover:brightness-75 transition-all",
              loading: "lazy"
            %>
            </div>
          <% else %>
            <div class="w-full h-48 bg-gray-200 mx-2 mt-2"></div>
          <% end %>
          <div class="px-2 py-1">
            <p><%= item.name %></p>
          </div>
        <% end %>
      </div>

      <div class="flex justify-between">
        <%= link_to "£#{item.price}", item_path(item), class: "px-2 py-1 flex-grow" %>

        <%= form_with url: basket_items_path(item_id: item.id), 
              method: :post,
              class: 'px-2 pb-2',
              data: { action: "submit->basket#submitForm" } do |form| %>
          <%= form.hidden_field :quantity, value: 1 %>
          <%= form.submit "Quick Add", class: 'btn-secondary' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="p-4">
  <div class="flex justify-start items-center w-full mb-2">    
    <%= form_with url: items_path, method: :get, local: true do %>
      <div class="flex items-center w-full sm:w-auto">
        <%= text_field_tag :query, params[:query], placeholder: "Search items", class: "input-class flex-grow sm:flex-grow-0 w-full sm:w-auto" %>
        <%= submit_tag "Search", class: "btn-primary ml-2 w-full sm:w-auto" %>
      </div>

      <!-- Sorting Filters -->
      <div class="flex overflow-x-auto gap-4 py-2 w-full no-scrollbar">
        <% filters = { 
          "price_asc" => "Price: Low to High", 
          "price_desc" => "Price: High to Low", 
          "name_asc" => "Name: A-Z", 
          "name_desc" => "Name: Z-A" 
        } %>
        <% filters.each do |key, label| %>
          <%= link_to items_path(query: params[:query], sort_by: key), class: "filter-tile #{'active' if params[:sort_by] == key}" do %>
            <%= label %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="flex justify-start mb-2">
    <p class="mx-2">
      <%= params[:query].present? ? "Results for '#{params[:query]}'" : "All products" %>
    </p>
    <p>|&nbsp; <%= @items.count %> item(s) </p>
  </div>
  
  <% if @items.empty? %>
    <p class="text-red-500 text-center font-bold py-4">No results found. Please try another search.</p>
  <% else %>
    <%= render 'item_list' %>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="p-4 flex justify-center items-center">
  <div class="flex flex-col lg:flex-row justify-center items-stretch w-full max-w-screen-lg">
    <div class="w-full lg:w-2/5 flex justify-center p-2">
      <img src="<%= @item.image_url %>" class="w-auto h-auto max-h-screen object-contain">
    </div>
    
    <div class="w-full lg:w-2/5 flex flex-col p-2 mx-auto lg:mx-0">
      <%= render 'item_details' %>

      <div class="mt-auto">
        <% if params[:query].present? %>
          <%= link_to "Back to all results", items_path(query: params[:query]), class: 'hover:text-lighterBlue' %>
        <% else %>
          <%= link_to "Back to all results", items_path, class: 'hover:text-lighterBlue' %>
        <% end %>
      </div>
    </div>
  </div>
</div>