config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # devise_scope :user do
  #   get 'my_account', to: 'users/registrations#edit', as: :my_account
  # end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"
  resources :items, only: [:index, :show]
  
  resources :basket_items, only: [:create, :update, :destroy]
  resource :basket, only: [:show]
  
  resources :wishlist_items, only: [:create, :destroy]
  resource :wishlist, only: [:show]
  
  resources :orders, only: [:new, :create, :index, :show] do
    member do
      get :confirmation
      delete :cancel
      patch :save_address
      patch :save_delivery_date 
    end
    resources :payments, only: [:new, :create] do
      get :success, on: :collection
    end
  end

  resources :deliveries, only: [] do
    collection do
      get :available_dates
    end
  end

  get 'api/address_lookup', to: 'addresses#lookup'
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :wishlist_items, dependent: :destroy
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def show
    @wishlist = current_user.wishlist
    @wishlist_items = @wishlist.wishlist_items.includes(:item)
  end
end

app/views/wishlists/_wishlist_item.html.erb
<div class="flex items-center bg-slate-50 drop-shadow m-2">
  <%= link_to item_path(wishlist_item.item) do %>
    <img src="<%= wishlist_item.item.image_url %>"
          alt="Item image"
          class="w-28 h-28 flex-shrink-0 object-contain p-1 mr-2 hover:brightness-125 transition-all">
  <% end %>
  <div class="flex flex-grow justify-between mr-2">
    <div class="flex flex-col flex-grow">
      <div class="flex justify-between items-start">
        <p class="pt-2 hover:text-lighterBlue">
          <%= link_to item_path(wishlist_item.item) do %>
            <%= wishlist_item.item.name %>
          <% end %>
        </p>
        <div>
          <%= button_to wishlist_item_path(wishlist_item),
              # 'Remove',
              method: :delete,
              class: 'mx-2 mt-2 text-red-700 hover:text-red-400',
              data: { confirm: 'Are you sure?' } do %>
                <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
      

      <div class="flex items-center py-2">
        <div>
          <div class="w-full flex justify-between items-center" data-controller="basket">
            <%= form_with url: basket_items_path(item_id: wishlist_item.item.id), 
                  method: :post, class: 'flex items-center',
                  data: { action: "submit->basket#submitForm" } do |form| %>
              <div class="flex">
                <p>Quantity:&nbsp;</p>
                <input type="number"
                      name="quantity"
                      value="1"
                      min="1"
                      max="<%= wishlist_item.item.stock %>"
                      class="w-10 bg-slate-50 text-center"
                      data-basket-target="quantityInput"
                      data-action="input->basket#updateHiddenQuantity">
              </div>
              <%= form.hidden_field :quantity, 
                  data: { basket_target: "hiddenQuantity" } %>
              <%= form.submit "Add to basket", class: 'btn-secondary ml-2 cursor-pointer' %>
            <% end %>
          </div>
        </div>
      </div>
      <p class="pb-2">
        £<%= wishlist_item.item.price %> per unit
      </p>
    </div>
    
  </div>
</div>

app/views/wishlists/show.html.erb
<div class="p-4 flex flex-col lg:flex-row">
  <div class="w-full lg:w-1/2">
    <h1 class="font-bold text-3xl p-1 text-darkBlue">My Wishlist</h1>
    <% if @wishlist_items.any? %>
      <% @wishlist_items.each do |wishlist_item| %>
        <%= render 'wishlist_item', wishlist_item: wishlist_item %>
      <% end %>

    <% else %>
      <p class="text-center mt-4">Your Wishlist is empty</p>
    <% end %>
    <%= link_to 'Continue Shopping', items_path, class: 'btn-secondary m-2' %>
  </div>

  <div class="w-full lg:w-1/2">
    <h1 class="font-bold text-3xl p-1 text-darkBlue">Another section</h1>
  </div>
</div>